name: Referral Program Management

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  track-referrals:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Referral Stats
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python backend/sub_agis/marketing/referral_tracker.py \
          --update \
          --notify

  reward-fulfillment:
    runs-on: ubuntu-latest
    needs: track-referrals
    steps:
    - uses: actions/checkout@v3
    - name: Process Rewards
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
      run: |
        python backend/sub_agis/marketing/referral_tracker.py \
          --process-rewards \
          --tier 1 \
          --tier 2 \
          --tier 3
